model:
  steps_to_predict: 72
  include_weekends: True
  

training:
  epochs: 200
  batch_size: 128
  sequence_length: 128
  lstm_units: 256
  dense_units: 64
  dropout_rate: 0.2
  learning_rate: 0.001
  loss_function: mse
  target_column: "Consumption"
  date_column: "DateTime"
  target_file: "electricity.csv"

datasets:
  weather.csv:
    file_path: "weather.csv"
    date_column: "Date time"
    frequency: "1D"
    datetime_format: "%Y-%m-%d"
    columns:
      - "Temperature" # All columns
      - "Wind Speed"
      - "Relative Humidity"
   

  electricity.csv:
    file_path: "electricity.csv"
    date_column: "DateTime"
    frequency: "1H"
    datetime_format: "%Y-%m-%d %H:%M:%S"
    columns:
      - "Consumption"
      - "Wind"
      - "Nuclear"
    target_column: "Consumption"

