model:
  steps_to_predict: 3
  include_weakends: True
  

training:
  epochs: 4
  batch_size: 64
  sequence_length: 4
  lstm_units: 64
  dense_units: 128
  dropout_rate: 0.1
  learning_rate: 0.001
  loss_function: mean_squared_error
  target_column: "Consumption"
  date_column: "DateTime"
  target_file: "electricity.csv"

datasets:
  weather.csv:
    file_path: "weather.csv"
    date_column: "Date time"
    frequency: "1D"
    datetime_format: "%Y-%m-%d"
    columns:
      - "Minimum Temperature"
      - "Maximum Temperature"
      - "Temperature"
   

  electricity.csv:
    file_path: "electricity.csv"
    date_column: "DateTime"
    frequency: "1H"
    datetime_format: "%Y-%m-%d %H:%M:%S"
    columns:
      - "Consumption"
      - "Wind"
      - "Nuclear"
    target_column: "Consumption"

setup:
  memory_limit: 6
