model:
  include_weekends: False
  steps_to_predict: 3

training:
  epochs: 40
  batch_size: 64
  sequence_length: 14
  lstm_units: 128
  dense_units: 64
  dropout_rate: 0.3
  learning_rate: 0.005
  loss_function: "huber"

  target_column: "Price"
  date_column: "Date"
  target_file: "daily_gold_price.csv"

datasets:
  daily_gold_price.csv:
    file_path: "daily_gold_price.csv"
    date_column: "Date"
    frequency: "1D"
    datetime_format: "%Y-%m-%d" # Matches your dataset
    columns:
      - "Price"

    target_column: "Price"

  inr_to_usd_exchange_rate.csv:
    file_path: "inr_to_usd_exchange_rate.csv"
    date_column: "Date"
    frequency: "1D"
    datetime_format: "%Y-%m-%d" # Matches your dataset
    columns:
      - "Open"
      - "High"
      - "Adj Close"
    
  # days.csv:
  #   file_path: "days.csv"
  #   date_column: "Date"
  #   frequency: "1D"
  #   datetime_format: "%Y-%m-%d" # Matches your dataset
  #   columns:
  #     - "Holiday"
  #     - "WeekDay"
  #     - "Weekend"


