# Input file configuration
input_file: /appz/sampledata/predict-3.0/web_traffic/daily-website-visitors.csv

# Output file configuration
output_file: "website_visitors_processed.csv"  # Name of the processed output file

# Date filtering
date_column: "Date"  # Column containing the date values
start_date: "2020-01-20"  # Start date for filtering (format: yyyy-mm-dd)
end_date: "2020-05-25"    # End date for filtering (format: yyyy-mm-dd)
date_format: "%Y-%m-%d"  # Desired format for the date column in the output

# Type casting configuration (optional)
type_casting:
  First.Time.Visits: int

# Rename columns (optional)
rename_columns:
  Day: "Day_of_week"  # Rename Day to Day_of_week

# Filters (conditions to apply to the dataset)
filters: {}  # No filters applied

# Required columns (columns to keep after processing)
required_columns: ['Day_of_week', 'Date', 'Page.Loads', 'Unique.Visits', 'First.Time.Visits', 'Returning.Visits']

# Warning message configuration for large datasets
warning_threshold: 50000  # Threshold for the number of rows
warning_message: "Warning: Your raw dataset has more than 50,000 rows."
