datasets:
  inputs:
    - file: "gold.csv"
      datetime_column: "Date"
      columns:
        - "Gold Price"
        - "Open Gold price"
        - "High Price"
        - "Low Price"
        - "Gold Volume"

    - file: "inrusd.csv"
      datetime_column: "Date"
      columns:
        - "Close"
        -  "Open"
        - "High"
        - "Low"
        - "Volume"
        - "Adj Close"
  target_column: "Gold Price"
  target_dataset_index: 0 # Specify the index of the dataset containing the target column
  primary_dataset_granularity: 'D' # Specify the granularity
  secondary_dataset_granularity: 'D' # Specify the granularity
splitting:
  steps_for_training: 2201   # Number of daily data points for training
  steps_for_prediction: 3  # N0umber of daily data points for prediction
training: 
  sequence_length: 1
  batch_size: 24
  epochs: 50
  density_ratio_number: 1 #  
model:
  lstm_units: 128
  learning_rate: 0.01
  high_feature_count: 4
results:
  file: "results.yaml"
  output_predictions: "predictions.csv"
